openapi: 3.0.3
info:
  title: Swagger Landing Page - OpenApi 3.0
  description: |-
    Definitions of HTTP services por API
  contact:
    email: milherf1@gmail.com
  version: 0.0.1-SNAPSHOT
servers:
  - url: https://localhost.swagger.io/api/v3/

tags:
  - name: precios
    description: Busqueda de precios por fecha de aplicación, cadena y producto

paths:
  /precios/busquedaPrecios:
    get:
      tags:
        - precios
      summary: Busqueda de precios por fecha de aplicación, cadena y por producto
      description: Busqueda de precios por fecha de aplicación, cadena y por producto
      operationId: getPrecios
      parameters:
        - name: fechaAplicacion
          in: query
          description: Fecha Aplicacion
          required: true
          schema:
            type: string
            format: date-time
        - name: cadenaId
          in: query
          description: Cadena del producto
          required: true
          schema:
            type: integer
            format: int64
        - name: productoId
          in: query
          description: Id del producto
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/preciosDTO'
        '400':
          description: Precios no encontrados


components:
  schemas:
    preciosDTO:
      properties:
        productoId:
          type: integer
          format: int64
          example: 35455
        cadenaId:
            type: integer
            format: int64
            example: 1
        tarifa:
            type: number
            format: double
        fecha:
            type: string
            format: datetime
        precio:
            type: number
            format: double